# Generated by Django 3.1 on 2023-05-30 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20200808_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='cplus_rating',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='dsa_rating',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='java_rating',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='no_challenges_solved',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='python_rating',
        ),
        migrations.AddField(
            model_name='candidate',
            name='matricula',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='numero',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='auth.user'),
            preserve_default=False,
        ),
    ]
