# Generated by Django 3.1 on 2023-05-30 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230530_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='usuario',
        ),
    ]
