# Generated by Django 3.1 on 2023-05-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_vote_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='eleitor',
            field=models.CharField(default='None', max_length=100, unique=True),
        ),
    ]
