# Generated by Django 3.1 on 2023-05-30 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_vote_eleitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(default='None', max_length=50, unique=True)),
                ('eleitor', models.CharField(default='None', max_length=100, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Candidate',
            new_name='Candidato',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.AddField(
            model_name='voto',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voto', to='main.candidato'),
        ),
    ]
