# Generated by Django 3.1 on 2023-05-30 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20230530_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voto',
            old_name='candidate',
            new_name='candidato',
        ),
    ]
